USE EMPRESA;


#contar todo mis departamentos
SELECT *
FROM PERSONALES;
SELECT *
FROM DEPARTAMENTOS;

DESC PERSONALES;

#CUANTAS PERSONAS TIENE CADA DEPARTAMENTO
SELECT COUNT(DEPARTAMENTO_ID) AS CANT_PERSONAS, D.NOMBRE
FROM PERSONALES AS P
INNER JOIN DEPARTAMENTOS AS D
ON D.ID = P.DEPARTAMENTO_ID
GROUP BY DEPARTAMENTO_ID;


#CUANTAS VECES SE REPITE EL NOMBRE DE UNA PERSONA EN CADA DEPARTAMENTO
-- SI EN EL GROUP BY LE HUBIERA PUESTO DEPARTAMENTO_ID SOLO HUBIERA CONTADO DE ESE Y RECUERDA QUE ESE GRUPO 
-- TIENE 5 DATOS NADA MAS ENTONCES LE PONGO DE NOMBRE GROUP BY PARA QUE ME CUENTE DE TODOS LOS NOMBRES REPETI2
SELECT COUNT(DEPARTAMENTO_ID) AS CANT_PERSON, DEPARTAMENTO_ID,NOMBRE
FROM PERSONALES
GROUP BY DEPARTAMENTO_ID,NOMBRE
ORDER BY CANT_PERSON ASC,DEPARTAMENTO_ID ASC,NOMBRE ASC;


# MOSTRAR CUANTOS EMPLEADOS HAY EN EL DEPARTAMENTO-2
#PODEMOS CREAR UNA COLUMNA FICTICIA
SELECT 'DEPARTAMENTO 2' DEPARTAMENTO, COUNT(*) TOTAL
FROM PERSONALES
WHERE DEPARTAMENTO_ID=2;

-- CUANTAS PERSONAS NO TIENE JEFE Y CUANTAS PERSONAS CORRESPONDE A CADA AREA
-- DEPARTAMENTO   |   TOTAL
-- 		1				10
-- 		2				3
-- 		3				5
-- 		4				4

#IS NULL MUY BUENA ES VEZDE USAR EL IGUAL BUENAZO
SELECT COUNT(*),P.NOMBRE,P.APELLIDO,D.NOMBRE,P.DEPARTAMENTO_ID,P.SUPERVISOR_ID
FROM PERSONALES AS P
INNER JOIN DEPARTAMENTOS AS D
ON D.ID=P.DEPARTAMENTO_ID
WHERE P.SUPERVISOR_ID IS NULL
GROUP BY DEPARTAMENTO_ID
ORDER BY 1 DESC;



SELECT PERSONALES.SUPERVISOR_ID
FROM PERSONALES
LEFT JOIN DEPARTAMENTOS
ON PERSONALES.DEPARTAMENTO_ID  != DEPARTAMENTOS.ID;
#WHERE PERSONALES.SUPERVISOR_ID = null;


-- MOSTRAR EL NOMBRE DEL DEPARTAMENTO Y SU CANTIDAD DE EMPLEADOS

-- 		DEPARTAMENTO		|		CANTIDAD DE EMPLEADOS
-- 		VENTAS				|				150
-- 		ADMINISTRACION		|				200
-- 		FINANZAS			|				85
-- 		MARKETING			|				56

SELECT D.NOMBRE,COUNT(P.ID) AS 'CANT_EMPLEADOS'
FROM DEPARTAMENTOS AS D
INNER JOIN PERSONALES AS P
ON D.ID = P.DEPARTAMENTO_ID
GROUP BY D.NOMBRE;





