# FUNCTIONES DE AGREGACION
# PROMEDIO AVG(COLUMN)
# MAXIMO MAX(COLUMN)
# MINIMO MIN(COLUMN)
# CONTAR COUNT(COLUMN)
# SUMAR SUM(COLUMN)
# PRIMERO FIRST(COLUMN)
# ULTIMO LAST(COLUMN)


#ORDEN QUE DEBEMOS SEGUIR
#SELECT COLUMNAS
#FROM TABLA - JOIN
#WHERE CONDICION
#GROUP BY AGRUPAMIENTOS
#ORDER BY COL ASC|DESC
#LIMIT 0
#OFFSET 0;
#REVISAR LA DOCUMENTACION SUPER BUENAZOOO
USE EMPRESA;

# limit SOLO MUESTRAME LAS 10 PRIMERAS PERSONAS SI LE PONES
# OFFSET NUMBER DIRAS SALTEATE ESTAS 10 PERSONAS Y MUESTRAME LAS 10COL siguientes
#UN DEFECTO QUE SOLO SE PODRA BUSCAR EN ESOS 10 DATOS NADA MAS PERO EN GENERAL
# NO SE VA PODER NI USANDO UN WHERE
#DESPUES DEL ORDEY BY PODEMOS USARR EL LIMIT Y EL OFFSET
SELECT *
FROM PERSONALES 
WHERE NOMBRE='PACOLA' LIMIT 10 OFFSET 10;


SELECT *
FROM PERSONALES
LIMIT 10 OFFSET 10;



