use empresa;
#una transition consite en qe todo debe cumplirse
#si todo el proceo se completa bien transtion LO CIERAS CON UN COMMIT
# UNA TRANSACTION ES UN PROCESO QUE REALIZA DICHA ACTIVIDAD 
#PUEDE AVER MUCHAS LINEAS EN UNA TRANSATION PERO CUANDO EMPIEZA A FALLAR PODEMOS
#ELIMINAR TODA ESA TRANSACTION HACIENDOLE UN ROLLBACK PARA QUE NO SE PIERDA TODO EL PROFE NI ME MALOGRE NADA 
#LO PONDRA TODO DSDE EL INICIO DESDE ANTES DE HACER LA TRANSATION ES SUPER BUENA 
#PERO SII TODO ESTA OK CERRAMOS LA TRANSATION HACIENDO UN COMMIT PARA QUE LAS MODIICACIONES
#SE GUARDEN EN LA BASE DED ATOS Y LA TRANSACTION TERMINE
select *
from personales;


#EMPIEZA LA TRANSACTION
#SELECCIONAMOS UNA PERSONA
#MODIFIAMOSEL NOMBRE DE ESA PERSONA
#SI TODO ESTA OK PARA CAMBIARLO LO CERRAMOS CON UN COMMIT FIN DErecetas_ingredientes LA TRANSACTION
#SI ESTA DESCONFORME ENTONCES ELIMINAMOS LA TRANSACTION PARA QUE ASI TODO ESTA DESDE EL INICIO
#MUY BUENAS PRACTICAS
#ROLLBACK UN CONJUNTOS DE OPERACIONES QUEDAN SIN EFECTO
start transaction;
SELECT *
FROM PERSONALES 
WHERE ID=1;

UPDATE PERSONALES SET NOMBRE='EDUARDO' WHERE ID=1;
COMMIT;
SELECT * 
FROM PERSONALES;
ROLLBACK;


ROLLBACK;#solo se usan las transactiones cuando hagamos modificacions a la base de datos
#ELIMINAR UN REGISTRO Y LUEGO ARREPENTIRME
START TRANSACTION;
SELECT *
FROM PERSONALES;

DELETE 
FROM PERSONALES
WHERE id=1;
SET SQL_SAFE_UPDATES=1;

UPDATE PERSONALES
SET APELLIDO="MAQUERA"
WHERE ID=1;
COMMIT;

USE EMPRESA;

SELECT * 
FROM DEPARTAMENTOS;
