-- CREAMOS LA BASE DE DATOS
CREATE DATABASE CLINICA;

-- USAMOS LA BASE DE DATOS QUE HEMOS CREADO
USE CLINICA;


-- CREAMOS TODAS LAS TABLAS
DROP TABLE PERSONAS;
CREATE TABLE PERSONAS(
	id INT PRIMARY KEY NOT NULL AUTO_INCREMENT UNIQUE,
    documento VARCHAR(20),
    tipo_documento ENUM('DNI','C.E.','PASAPORTE'),
    nombre VARCHAR(50) NOT NULL,
    apellido VARCHAR(50) NOT NULL,
    correo VARCHAR(50) UNIQUE,
    sexo ENUM('FEMENINO','MASCULINO','NOBINARIO') NOT NULL,
    fecha_nacimiento DATE NOT NULL
);

-- BRINDA UNA DESCRIPCION DE LA ESTRUCTURA DE COMO ESTA FORMADA NUESTRA TABLA
DESC PERSONAS;

-- INSERTAMOS VALORES A NUESTRA TABLA INSERTA 1 REGITRO
INSERT INTO PERSONAS(DOCUMENTO,TIPO_DOCUMENTO,NOMBRE,APELLIDO,CORREO,SEXO,FECHA_NACIMIENTO) 
VALUES('10','DNI','JHONAEL','MAQUERA','JHONAEL@GMAIL.COM','MASCULINO','1992-08-17');

-- CUANDO INSERTAMOS MAS DE 1 REGISTRO PODEMOS OBVIAR ALGUNAS COSAS
INSERT INTO PERSONAS(DOCUMENTO,TIPO_DOCUMENTO,NOMBRE,APELLIDO,CORREO,SEXO,FECHA_NACIMIENTO)VALUES
('11','PASAPORTE','AGUSTIN','COHAILA','AGUSTIN@GMAIL.COM','NOBINARIO','1995-07-23'),
('12','C.E.','WILLY','ALAVE','WILLY@GAMIL.COM','FEMENINO','1989-12-25');

INSERT INTO PERSONAS(DOCUMENTO,TIPO_DOCUMENTO,NOMBRE,APELLIDO,CORREO,SEXO,FECHA_NACIMIENTO)VALUES
('13','PASAPORTE','AGUSTIN','COHAILA','AGUSsTIN@GMAIL.COM','NOBINARIO','1995-07-23'),
('14','C.E.','WILLY','ALAVE','WILLsY@GAMIL.COM','FEMENINO','1989-12-25');

-- INDICAMOS QUE ATRIBUTOS DESEAMOS OBTENER DE ESTA CONSULTA
SELECT *
FROM medicos;

-- ALTER TABLE PERMITE AGREGAR, ELIMINAR,MODIFICAR UNA COLUMNA 
-- OJO PODEMOS AGREGAR ATRIBUTOS A LA COLUMNA
-- ALTER TABLE SOLAMENTE SE USA PARA LAS COLUMNAS
-- AGREGAR UNA NUEVA COLUMNA
ALTER TABLE PERSONAS ADD COLUMN TELEFONO VARCHAR(25);
-- ELIMINAR UNA COLUMNA
ALTER TABLE PERSONAS DROP COLUMN TELEFONO;
-- MODIFICAR EL TIPO DE DATO DE UNA COLUMNA
ALTER TABLE PERSONAS MODIFY  COLUMN FECHA_NACIMIENTO VARCHAR(10) NOT NULL;
-- CAMBIAR EL NOMBRE DE UNA COLUMNA
ALTER TABLE PERSONAS RENAME COLUMN TELEFONO TO CELULAR;
-- CAMBIAR EL NOMBRE DE UNA COLUMNA Y SU TIPO DE DATO TAMBIEN
ALTER TABLE PERSONAS CHANGE COLUMN CELULAR FONITO INT;

-- alter table libros  add primary key (codigo); //EJEMPLO PAR ADD CLAVE PRIMARY A UNA COLUMN
-- AQUI DICE QUE VOY AGREGAR UNA CLAVE FORANEA ES IGUAL PAR EL PRIMARY KEY

ALTER TABLE PERSONAS ADD FOREIGN KEY (CURSO_ID)references CURSO(ID);
-- para agregar,modificaro eliminar PARA PODER USAR ESTOS METODOS Y UPDATE DELETE 
-- DEBE SER SIEMPRE CON LA CONDICION WHERE E INDICANDO QUE ID DESEA ELIMINAR
-- XK ANDAMOS EN EL MODO SEGURO
-- agregar insert into

DELETE FROM PERSONAS
WHERE ID=1;

UPDATE PERSONAS
SET NOMBRE='LORENZO'
WHERE ID=2;


select * 
from personas;


DROP TABLE PERSONAS;
DROP TABLE cliente;

-- EMPEZMOS A CREAR NUESTRA TABLA DE CLINICA

CREATE TABLE MEDICOS(
id INT PRIMARY KEY NOT NULL UNIQUE AUTO_INCREMENT,
cmp VARCHAR(5) NOT NULL,
nombre VARCHAR(50) NOT NULL,
apellido VARCHAR(50) NOT NULL
);

INSERT INTO MEDICOS(CMP,NOMBRE,APELLIDO)VALUES
('11','JAVIER','AJROTA'),
('22','NASHITO','RAMOS'),
('33','ELIZABETH','CHAMBI'),
('44','JHONATAN','MAQUERA'),
('55','KARINE','FELICIANO');

INSERT INTO MEDICOS(CMP,NOMBRE,APELLIDO) VALUES
('777','RUTH','LOMA');

SELECT *
FROM MEDICOS;

UPDATE MEDICOS
SET APELLIDO='KARINE'
WHERE ID=5;

DELETE FROM MEDICOS
WHERE ID=6;

SELECT * 
FROM MEDICOS;

UPDATE MEDICOS
SET APELLIDO='COHAILA'
WHERE ID=5;

SELECT *
FROM MEDICOS;

ALTER TABLE MEDICOS ADD COLUMN TELEFONO VARCHAR(25);
ALTER TABLE MEDICOS RENAME COLUMN TELEFONO TO CELULAR;
ALTER TABLE MEDICOS CHANGE COLUMN CELULAR  FONO INT;

SELECT *
FROM MEDICOS;



-- LISTA DE TABLAS
SHOW TABLES;


SELECT * 
FROM PERSONAS;

select *
from historial_vacunaciones;

drop table historial_vacunaciones;
CREATE TABLE HISTORIAL_VACUNACIONES(
id INT PRIMARY KEY NOT NULL UNIQUE AUTO_INCREMENT,
vacuna ENUM('PFIZER','SINOPHARM','ASTRAZENECA'),
lote VARCHAR(10),
fecha DATE,
-- creando la foreing key
-- 1ro creamos los campos
medico_id int,
paciente_id int,

-- recien creamos las relaciones
FOREIGN KEY (medico_id) references medicos(id),
FOREIGN KEY (paciente_id) references personas(id)

);

INSERT INTO HISTORIAL_VACUNACIONES(vacuna,lote,medico_id,paciente_id,fecha) VALUES
('PFIZER','678',1,1,'2020-02-01'),
('PFIZER','185',1,6,'2020-03-20'),
('SINOPHARM','158',2,3,'2020-04-05'),
('SINOPHARM','995',2,4,now()),
('ASTRAZENECA','853',2,4,now());

-- no puedes eliminar una tabla cuando ya esta relacionada ojo
-- debes eliminar la tabla anterior para recien poder
select *
from HISTORIAL_VACUNACIONES;


show tables;


SELECT *
FROM HISTORIAL_VACUNACIONES
INNER JOIN MEDICOS
ON HISTORIAL_VACUNACIONES.MEDICO_ID=MEDICOS.ID;


SELECT *
FROM HISTORIAL_VACUNACIONES
INNER JOIN MEDICOS
ON HISTORIAL_VACUNACIONES.MEDICO_ID = MEDICOS.ID
INNER JOIN PERSONAS
ON HISTORIAL_VACUNACIONES.PACIENTE_ID=PERSONAS.ID;



-- ----------------------
CREATE DATABASE TASK_MANAGER ;
USE TASK_MANAGER;

-- ----------------------


-- data de recetas
INSERT INTO RECETAS (nombre, porcion)
VALUES(
        'AGUACATES RELLENOS DE GAMBAS Y PALITOS DE CANGREJO',
        'MEDIANO'
    );
INSERT INTO RECETAS (nombre, porcion)
VALUES('ALBONDIGAS AL HORNO', 'PERSONAL');
INSERT INTO RECETAS (nombre, porcion)
VALUES('ALBONDIGAS AL HORNO CON VERDURAS', 'FAMILIAR');
INSERT INTO RECETAS (nombre, porcion)
VALUES(
        'ALBONDIGAS CASERAS EN SALSA DE TOMATE',
        'MEDIANO'
    );productosproductos
INSERT INTO RECETAS (nombre, porcion)
VALUES('ALBÓNDIGAS CASERAS SIN FREÍR', 'PERSONAL');
INSERT INTO RECETAS (nombre, porcion)
VALUES(
        'ALBONDIGAS DE BACALAO EN SALSA VERDE',
        'FAMILIAR'
    );
INSERT INTO RECETAS (nombre, porcion)
VALUES('ALBONDIGAS DE CALABACIN', 'MEDIANO');
INSERT INTO RECETAS (nombre, porcion)
VALUES(
        'ALBÓNDIGAS DE CARNE EN SALSA VERDE PASO A PASO',
        'PERSONAL'
    );
INSERT INTO RECETAS (nombre, porcion)
VALUES('ALBONDIGAS DE PESCADO receta', 'FAMILIAR');
INSERT INTO RECETAS (nombre, porcion)
VALUES(
        'ALBONDIGAS DE POLLO AL CURRY EN SALSA DE COÑAC',
        'MEDIANO'
    );
INSERT INTO RECETAS (nombre, porcion)
VALUES(
        'ALBONDIGAS DE POLLO EN SALSA DE ALMENDRAS',
        'PERSONAL'
    );
INSERT INTO RECETAS (nombre, porcion)
VALUES(
        'ALBONDIGAS DE POLLO EN SALSA DE TOMATE',
        'FAMILIAR'
    );
INSERT INTO RECETAS (nombre, porcion)
VALUES(
        'ALBONDIGAS DE POLLO EN SALSA ESPAÑOLA',
        'MEDIANO'
    );
INSERT INTO RECETAS (nombre, porcion)
VALUES('ALBONDIGAS EN SALSA ESPAÑOLA', 'PERSONAL');
INSERT INTO RECETAS (nombre, porcion)
VALUES('ALCACHOFAS CON ALMEJAS', 'FAMILIAR');
INSERT INTO RECETAS (nombre, porcion)
VALUES('ALCACHOFAS CON JAMON', 'MEDIANO');
INSERT INTO RECETAS (nombre, porcion)
VALUES('ALIOLI CASERO SIN HUEVO receta', 'PERSONAL');
INSERT INTO RECETAS (nombre, porcion)
VALUES(
        'ALITAS DE POLLO A LA BARBACOA AL HORNO',
        'FAMILIAR'
    );
INSERT INTO RECETAS (nombre, porcion)
VALUES('ALITAS DE POLLO A LA CERVEZA', 'MEDIANO');
INSERT INTO RECETAS (nombre, porcion)
VALUES('ALITAS DE POLLO ADOBADAS AL HORNO', 'PERSONAL');
INSERT INTO RECETAS (nombre, porcion)
VALUES('ALITAS DE POLLO AL AJILLO', 'FAMILIAR');
INSERT INTO RECETAS (nombre, porcion)
VALUES(
        'ALITAS DE POLLO AL AJILLO ASADAS AL HORNO',
        'MEDIANO'
    );
INSERT INTO RECETAS (nombre, porcion)
VALUES(
        'ALITAS DE POLLO AL HORNO MARINADAS CON MIEL Y MOSTAZA',
        'PERSONAL'
    );
INSERT INTO RECETAS (nombre, porcion)
VALUES(
        'ALITAS DE POLLO BUFFALO WINGS receta',
        'FAMILIAR'
    );
INSERT INTO RECETAS (nombre, porcion)
VALUES('ALITAS DE POLLO FRITAS', 'MEDIANO');
INSERT INTO RECETAS (nombre, porcion)
VALUES('ALITAS DE POLLO MARINADAS CON LIMÓN', 'PERSONAL');
INSERT INTO RECETAS (nombre, porcion)
VALUES('ALMEJAS A LA MARINERA', 'FAMILIAR');
INSERT INTO RECETAS (nombre, porcion)
VALUES('ALMUERZOS FACILES Y RAPIDOS DE HACER', 'MEDIANO');
INSERT INTO RECETAS (nombre, porcion)
VALUES('ALUBIAS BLANCAS CON ALMEJAS', 'PERSONAL');
INSERT INTO RECETAS (nombre, porcion)
VALUES('ALUBIAS BLANCAS CON VERDURAS', 'FAMILIAR');
INSERT INTO RECETAS (nombre, porcion)
VALUES('ALUBIAS ROJAS CON CHORIZO Y MORCILLA', 'MEDIANO');
INSERT INTO RECETAS (nombre, porcion)
VALUES('ALUBIAS ROJAS CON SACRAMENTOS', 'PERSONAL');
INSERT INTO RECETAS (nombre, porcion)
VALUES('ALUBIAS ROJAS CON VERDURAS', 'FAMILIAR');
INSERT INTO RECETAS (nombre, porcion)
VALUES(
        'AREPAS VENEZOLANAS RELLENAS DE POLLO Y AGUACATE',
        'MEDIANO'
    );
INSERT INTO RECETAS (nombre, porcion)
VALUES('AROS DE CEBOLLA FACILES', 'PERSONAL');
INSERT INTO RECETAS (nombre, porcion)
VALUES('AROS DE CEBOLLA receta facil', 'FAMILIAR');
INSERT INTO RECETAS (nombre, porcion)
VALUES('ARROZ A LA CUBANA CON PLATANO', 'MEDIANO');
INSERT INTO RECETAS (nombre, porcion)
VALUES('ARROZ AL HORNO CON POLLO Y VERDURAS', 'PERSONAL');
INSERT INTO RECETAS (nombre, porcion)
VALUES('ARROZ AL SEÑORITO receta', 'FAMILIAR');
INSERT INTO RECETAS (nombre, porcion)
VALUES('ARROZ BLANCO CON POLLO Y VERDURAS', 'MEDIANO');
INSERT INTO RECETAS (nombre, porcion)
VALUES('ARROZ BLANCO SUELTO receta', 'PERSONAL');
INSERT INTO RECETAS (nombre, porcion)
VALUES('ARROZ CALDOSO CON BOGAVANTE', 'FAMILIAR');
INSERT INTO RECETAS (nombre, porcion)
VALUES('ARROZ CALDOSO CON POLLO', 'MEDIANO');
INSERT INTO RECETAS (nombre, porcion)
VALUES('ARROZ CALDOSO DE MARISCO facil', 'PERSONAL');
INSERT INTO RECETAS (nombre, porcion)
VALUES('ARROZ CON LECHE', 'FAMILIAR');
INSERT INTO RECETAS (nombre, porcion)
VALUES('ARROZ CON LECHE DE COCO', 'MEDIANO');
INSERT INTO RECETAS (nombre, porcion)
VALUES('ARROZ CON POLLO AL TOQUE DE CURRY', 'PERSONAL');
INSERT INTO RECETAS (nombre, porcion)
VALUES('ARROZ CON POLLO Y VERDURAS receta', 'FAMILIAR');
INSERT INTO RECETAS (nombre, porcion)
VALUES('ARROZ CON VERDURAS receta', 'MEDIANO');
INSERT INTO RECETAS (nombre, porcion)
VALUES('ARROZ FRITO CHINO CON VERDURAS', 'PERSONAL');
INSERT INTO RECETAS (nombre, porcion)
VALUES(
        'ARROZ TRES DELICIAS CHINO receta original',
        'FAMILIAR'
    );
INSERT INTO RECETAS (nombre, porcion)
VALUES('ARROZ VIUDO CON VERDURAS', 'MEDIANO');
INSERT INTO RECETAS (nombre, porcion)
VALUES('ATUN A LA PLANCHA CON AJO Y PEREJIL', 'PERSONAL');
INSERT INTO RECETAS (nombre, porcion)
VALUES('ATUN A LA PLANCHA CON SOJA', 'FAMILIAR');
INSERT INTO RECETAS (nombre, porcion)
VALUES('ATUN AL AJILLO', 'MEDIANO');
INSERT INTO RECETAS (nombre, porcion)
VALUES('ATUN AL HORNO CON PATATAS Y CEBOLLA', 'PERSONAL');
INSERT INTO RECETAS (nombre, porcion)
VALUES('ATUN CON TOMATE receta', 'FAMILIAR');
INSERT INTO RECETAS (nombre, porcion)
VALUES('BACALAO AL PIL PIL', 'MEDIANO');
INSERT INTO RECETAS (nombre, porcion)
VALUES(
        'BACALAO FRITO CON CEBOLLA CARAMELIZADA',
        'PERSONAL'
    );
INSERT INTO RECETAS (nombre, porcion)
VALUES(
        'BACON CHEESE FRIES – patatas del foster hollywood',
        'FAMILIAR'
    );
INSERT INTO RECETAS (nombre, porcion)
VALUES(
        'BANDERILLAS DE SALCHICHA CON QUESO MUY FÁCILES DE PREPARAR',
        'MEDIANO'
    );
INSERT INTO RECETAS (nombre, porcion)
VALUES('BANDERILLAS DE SALCHICHA O CORNDOGS', 'PERSONAL');
INSERT INTO RECETAS (nombre, porcion)
VALUES('BECHAMEL SIN MANTEQUILLA', 'FAMILIAR');
INSERT INTO RECETAS (nombre, porcion)
VALUES('BERENJENAS A LA PARMESANA', 'MEDIANO');
INSERT INTO RECETAS (nombre, porcion)
VALUES(
        'BERENJENAS CON TOMATE Y QUESO AL HORNO',
        'PERSONAL'
    );
INSERT INTO RECETAS (nombre, porcion)
VALUES('BERENJENAS RELLENAS DE CARNE PICADA', 'FAMILIAR');
INSERT INTO RECETAS (nombre, porcion)
VALUES(
        'BERENJENAS RELLENAS DE VERDURA AL HORNO',
        'MEDIANO'
    );
INSERT INTO RECETAS (nombre, porcion)
VALUES('BIZCOCHO CASERO CON 3 INGREDIENTES', 'PERSONAL');
INSERT INTO RECETAS (nombre, porcion)
VALUES(
        'BIZCOCHO CASERO RELLENO DE CHOCOLATE',
        'FAMILIAR'
    );
INSERT INTO RECETAS (nombre, porcion)
VALUES('BIZCOCHO DE CALABAZA', 'MEDIANO');
INSERT INTO RECETAS (nombre, porcion)
VALUES('BIZCOCHO DE CHOCOLATE ESPONJOSO', 'PERSONAL');
INSERT INTO RECETAS (nombre, porcion)
VALUES('BIZCOCHO DE CHOCOLATE receta', 'FAMILIAR');
INSERT INTO RECETAS (nombre, porcion)
VALUES('BIZCOCHO DE LECHE ESPONJOSO CASERO', 'MEDIANO');
INSERT INTO RECETAS (nombre, porcion)
VALUES('BIZCOCHO DE LIMÓN', 'PERSONAL');
INSERT INTO RECETAS (nombre, porcion)
VALUES('BIZCOCHO DE MANZANA', 'FAMILIAR');
INSERT INTO RECETAS (nombre, porcion)
VALUES('BIZCOCHO DE NARANJA receta', 'MEDIANO');
INSERT INTO RECETAS (nombre, porcion)
VALUES('BIZCOCHO DE PLATANO', 'PERSONAL');
INSERT INTO RECETAS (nombre, porcion)
VALUES('BIZCOCHO DE YOGUR NATURAL', 'FAMILIAR');
INSERT INTO RECETAS (nombre, porcion)
VALUES('BIZCOCHO DE ZANAHORIA receta', 'MEDIANO');
INSERT INTO RECETAS (nombre, porcion)
VALUES('BIZCOCHO SIN HUEVO', 'PERSONAL');
INSERT INTO RECETAS (nombre, porcion)
VALUES(
        'BOCADITOS DE HOJALDRE DULCE BAÑADOS CON MIEL',
        'FAMILIAR'
    );
INSERT INTO RECETAS (nombre, porcion)
VALUES('BOLAS DE ARROZ ITALIANAS RELLENAS', 'MEDIANO');
INSERT INTO RECETAS (nombre, porcion)
VALUES(
        'BOLAS DE PATATA RELLENAS DE CARNE PICADA',
        'PERSONAL'
    );
INSERT INTO RECETAS (nombre, porcion)
VALUES(
        'BOLITAS DE ARROZ Y QUESO RECETA CASERA',
        'FAMILIAR'
    );
INSERT INTO RECETAS (nombre, porcion)
VALUES('BOLITAS DE CARNE PICADA CON QUESO', 'MEDIANO');
INSERT INTO RECETAS (nombre, porcion)
VALUES('BOLITAS DE CHOCOLATE BLANCO', 'PERSONAL');
INSERT INTO RECETAS (nombre, porcion)
VALUES('BOLITAS DE COCO Y CHOCOLATE', 'FAMILIAR');
INSERT INTO RECETAS (nombre, porcion)
VALUES('BOLITAS DE OREO receta', 'MEDIANO');
INSERT INTO RECETAS (nombre, porcion)
VALUES('BOLITAS DE PATATA O PAPAS', 'PERSONAL');
INSERT INTO RECETAS (nombre, porcion)
VALUES('BOLITAS DE QUESO receta', 'FAMILIAR');
INSERT INTO RECETAS (nombre, porcion)
VALUES('BOMBONES DE CHOCOLATE BLANCO Y COCO', 'MEDIANO');
INSERT INTO RECETAS (nombre, porcion)
VALUES('BOMBONES RELLENOS DE NUTELLA', 'PERSONAL');
INSERT INTO RECETAS (nombre, porcion)
VALUES('BONITO CON TOMATE JUGOSO', 'FAMILIAR');
INSERT INTO RECETAS (nombre, porcion)
VALUES(
        'BOQUERONES EN VINAGRE receta de la abuela',
        'MEDIANO'
    );
INSERT INTO RECETAS (nombre, porcion)
VALUES('BRAZO GITANO DE NATA', 'PERSONAL');
INSERT INTO RECETAS (nombre, porcion)
VALUES('BROCHETAS DE FRUTA CON CHOCOLATE', 'FAMILIAR');
INSERT INTO RECETAS (nombre, porcion)
VALUES('BROCHETAS DE POLLO A LA PLANCHA', 'MEDIANO');
INSERT INTO RECETAS (nombre, porcion)
VALUES('BROCHETAS DE POLLO AL CURRY', 'PERSONAL');
INSERT INTO RECETAS (nombre, porcion)
VALUES(
        'BROCHETAS DE POLLO MARINADO CON MOSTAZA Y MIEL',
        'FAMILIAR'
    );
INSERT INTO RECETAS (nombre, porcion)
VALUES(
        'BROCHETAS DE VERDURAS ASADAS AL HORNO',
        'MEDIANO'
    );
INSERT INTO RECETAS (nombre, porcion)
VALUES('BROWNIE DE CASTAÑAS', 'PERSONAL');
INSERT INTO RECETAS (nombre, porcion)
VALUES('BROWNIE DE CHOCOLATE Y NUECES', 'FAMILIAR');
INSERT INTO RECETAS (nombre, porcion)
VALUES('BROWNIE EN TAZA SIN AZUCAR', 'MEDIANO');
INSERT INTO RECETAS (nombre, porcion)
VALUES('BUEY DE MAR RELLENO receta', 'PERSONAL');
INSERT INTO RECETAS (nombre, porcion)
VALUES('BUÑUELOS DE BACALAO', 'FAMILIAR');
INSERT INTO RECETAS (nombre, porcion)
VALUES('BUÑUELOS DE CALABAZA', 'MEDIANO');
INSERT INTO RECETAS (nombre, porcion)
VALUES('CABRITO AL HORNO CON PATATAS', 'PERSONAL');
INSERT INTO RECETAS (nombre, porcion)
VALUES('CACHOPO DE TERNERA', 'FAMILIAR');
INSERT INTO RECETAS (nombre, porcion)
VALUES('CALABACIN AL HORNO CON QUESO', 'MEDIANO');
INSERT INTO RECETAS (nombre, porcion)
VALUES(
        'CALABACIN REBOZADO CON JAMON Y QUESO',
        'PERSONAL'
    );
INSERT INTO RECETAS (nombre, porcion)
VALUES('CALABACIN RELLENO DE JAMON Y QUESO', 'FAMILIAR');
INSERT INTO RECETAS (nombre, porcion)
VALUES('CALABACINES RELLENOS DE CARNE', 'MEDIANO');
INSERT INTO RECETAS (nombre, porcion)
VALUES('CALABAZA GRATINADA CON QUESO', 'PERSONAL');
INSERT INTO RECETAS (nombre, porcion)
VALUES('CALABAZA RELLENA DE CARNE AL HORNO', 'FAMILIAR');
INSERT INTO RECETAS (nombre, porcion)
VALUES(
        'CALABAZA RELLENA DE VERDURAS AL HORNO',
        'MEDIANO'
    );
INSERT INTO RECETAS (nombre, porcion)
VALUES('CALAMARES EN SU TINTA', 'PERSONAL');
INSERT INTO RECETAS (nombre, porcion)
VALUES('CALAMARES ENCEBOLLADOS CON TOMATE', 'FAMILIAR');
INSERT INTO RECETAS (nombre, porcion)
VALUES('CALDERETA DE CORDERO CON PATATAS', 'MEDIANO');
INSERT INTO RECETAS (nombre, porcion)
VALUES('CALDO DE POLLO RECETA', 'PERSONAL');
INSERT INTO RECETAS (nombre, porcion)
VALUES('CALLOS A LA MADRILEÑA receta facil', 'FAMILIAR');
INSERT INTO RECETAS (nombre, porcion)
VALUES('CALZONE O PIZZA ENROLLADA', 'MEDIANO');
INSERT INTO RECETAS (nombre, porcion)
VALUES('CANELONES DE ATUN Y HUEVO', 'PERSONAL');
INSERT INTO RECETAS (nombre, porcion)
VALUES(
        'CANELONES DE CALABACIN RELLENOS DE ATUN',
        'FAMILIAR'
    );
INSERT INTO RECETAS (nombre, porcion)
VALUES('CANELONES DE CARNE PICADA Y BECHAMEL', 'MEDIANO');
INSERT INTO RECETAS (nombre, porcion)
VALUES(
        'CANELONES RELLENOS DE ESPINACAS Y GAMBAS',
        'PERSONAL'
    );
INSERT INTO RECETAS (nombre, porcion)
VALUES('CARAMELO LÍQUIDO CASERO', 'FAMILIAR');
INSERT INTO RECETAS (nombre, porcion)
VALUES('CARNE GUISADA EN OLLA RAPIDA', 'MEDIANO');
INSERT INTO RECETAS (nombre, porcion)
VALUES('CARNE MECHADA DE TERNERA receta', 'PERSONAL');
INSERT INTO RECETAS (nombre, porcion)
VALUES(
        'CARRILLERAS DE CERDO EN SALSA DE TOMATE',
        'FAMILIAR'
    );
INSERT INTO RECETAS (nombre, porcion)
VALUES(
        'CARRILLERAS DE CERDO EN SALSA DE VINO TINTO receta',
        'MEDIANO'
    );
INSERT INTO RECETAS (nombre, porcion)
VALUES(
        'CARRILLERAS DE TERNERA AL VINO TINTO',
        'PERSONAL'
    );
INSERT INTO RECETAS (nombre, porcion)
VALUES('CEBOLLA CARAMELIZADA FACIL', 'FAMILIAR');
INSERT INTO RECETAS (nombre, porcion)
VALUES('CEBOLLAS RELLENAS DE CARNE AL HORNO', 'MEDIANO');
INSERT INTO RECETAS (nombre, porcion)
VALUES('CENAS RAPIDAS SALUDABLES Y LIGERAS', 'PERSONAL');
INSERT INTO RECETAS (nombre, porcion)
VALUES('CERDO AGRIDULCE CHINO', 'FAMILIAR');
INSERT INTO RECETAS (nombre, porcion)
VALUES('CHAMPIÑONES AL AJILLO receta', 'MEDIANO');
INSERT INTO RECETAS (nombre, porcion)
VALUES('CHAMPIÑONES EN SALSA OSCURA', 'PERSONAL');
INSERT INTO RECETAS (nombre, porcion)
VALUES('CHAMPIÑONES EN SALSA VERDE', 'FAMILIAR');
INSERT INTO RECETAS (nombre, porcion)
VALUES(
        'CHAMPIÑONES RELLENOS AL HORNO CON JAMON Y QUESO',
        'MEDIANO'
    );
INSERT INTO RECETAS (nombre, porcion)
VALUES('CHILI CON CARNE receta original', 'PERSONAL');
INSERT INTO RECETAS (nombre, porcion)
VALUES('CHIMICHURRI ARGENTINO receta', 'FAMILIAR');
INSERT INTO RECETAS (nombre, porcion)
VALUES('CHOP SUEY DE TERNERA CHINO', 'MEDIANO');
INSERT INTO RECETAS (nombre, porcion)
VALUES('CHORIZO A LA SIDRA', 'PERSONAL');
INSERT INTO RECETAS (nombre, porcion)
VALUES('CHULETON A LA PLANCHA PERFECTO', 'FAMILIAR');
INSERT INTO RECETAS (nombre, porcion)
VALUES('CLAFOUTIS DE CEREZAS receta original', 'MEDIANO');
INSERT INTO RECETAS (nombre, porcion)
VALUES('CLASES DE LEVADURAS USOS', 'PERSONAL');
INSERT INTO RECETAS (nombre, porcion)
VALUES('COCER ARROZ BLANCO PERFECTO', 'FAMILIAR');
INSERT INTO RECETAS (nombre, porcion)
VALUES(
        'COCER COLIFLOR AL VAPOR EN OLLA EXPRESS',
        'MEDIANO'
    );
INSERT INTO RECETAS (nombre, porcion)
VALUES('COCER ESPARRAGOS VERDES TRIGUEROS', 'PERSONAL');
INSERT INTO RECETAS (nombre, porcion)
VALUES('COCER ESPINACAS', 'FAMILIAR');
INSERT INTO RECETAS (nombre, porcion)
VALUES(
        'COCER LANGOSTINOS: TIEMPOS Y OTROS TRUCOS',
        'MEDIANO'
    );
INSERT INTO RECETAS (nombre, porcion)
VALUES('COCER PATATAS PERFECTAS', 'PERSONAL');
INSERT INTO RECETAS (nombre, porcion)
VALUES('COCER PULPO', 'FAMILIAR');
INSERT INTO RECETAS (nombre, porcion)
VALUES('COCHINILLO ASADO AL HORNO', 'MEDIANO');
INSERT INTO RECETAS (nombre, porcion)
VALUES('CODORNICES EN ESCABECHE receta', 'PERSONAL');
INSERT INTO RECETAS (nombre, porcion)
VALUES('COLES DE BRUSELAS CON JAMON', 'FAMILIAR');
INSERT INTO RECETAS (nombre, porcion)
VALUES('COLIFLOR AL HORNO EMPANADA', 'MEDIANO');
INSERT INTO RECETAS (nombre, porcion)
VALUES('COLIFLOR COCIDA CON PATATAS', 'PERSONAL');
INSERT INTO RECETAS (nombre, porcion)
VALUES(
        'COLIFLOR GRATINADA CON QUESO Y BECHAMEL',
        'FAMILIAR'
    );
INSERT INTO RECETAS (nombre, porcion)
VALUES('COLIFLOR REBOZADA CON CERVEZA', 'MEDIANO');
INSERT INTO RECETAS (nombre, porcion)
VALUES('COLIFLOR TRES DELICIAS', 'PERSONAL');
INSERT INTO RECETAS (nombre, porcion)
VALUES('COMIDA AMERICANA RECETAS FACILES', 'FAMILIAR');
INSERT INTO RECETAS (nombre, porcion)
VALUES('COMIDA CHINA', 'MEDIANO');
INSERT INTO RECETAS (nombre, porcion)
VALUES('COMIDA ESPAÑOLA', 'PERSONAL');
INSERT INTO RECETAS (nombre, porcion)
VALUES('COMIDA FRANCESA FACIL', 'FAMILIAR');
INSERT INTO RECETAS (nombre, porcion)
VALUES('COMIDA ITALIANA RECETAS FACILES', 'MEDIANO');
INSERT INTO RECETAS (nombre, porcion)
VALUES('COMIDA MEXICANA', 'PERSONAL');
INSERT INTO RECETAS (nombre, porcion)
VALUES(
        'COMO CUIDAR EL ACEITE DE LA FREIDORA PARA QUE DURE MUCHO MÁS TIEMPO',
        'FAMILIAR'
    );
INSERT INTO RECETAS (nombre, porcion)
VALUES('COMPOTA DE MANZANA', 'MEDIANO');
INSERT INTO RECETAS (nombre, porcion)
VALUES('CONEJO A LA CAZADORA GUISADO', 'PERSONAL');
INSERT INTO RECETAS (nombre, porcion)
VALUES('CONEJO AL AJILLO receta', 'FAMILIAR');
INSERT INTO RECETAS (nombre, porcion)
VALUES('CONEJO AL HORNO CON PATATAS', 'MEDIANO');
INSERT INTO RECETAS (nombre, porcion)
VALUES('CONEJO GUISADO CON CHAMPIÑONES', 'PERSONAL');
INSERT INTO RECETAS (nombre, porcion)
VALUES('CONEJO GUISADO CON VERDURAS', 'FAMILIAR');
INSERT INTO RECETAS (nombre, porcion)
VALUES('CONGELAR CROQUETAS YA REBOZADAS', 'MEDIANO');
INSERT INTO RECETAS (nombre, porcion)
VALUES('CORDERO ASADO AL HORNO', 'PERSONAL');
INSERT INTO RECETAS (nombre, porcion)
VALUES('CORDERO GUISADO RECETA TRADICIONAL', 'FAMILIAR');
INSERT INTO RECETAS (nombre, porcion)
VALUES(
        'CORDON BLEU DE POLLO RELLENO DE JAMÓN Y QUESO',
        'MEDIANO'
    );
INSERT INTO RECETAS (nombre, porcion)
VALUES('CORDON BLEU DE TERNERA', 'PERSONAL');
INSERT INTO RECETAS (nombre, porcion)
VALUES('CORVINA A LA PLANCHA CON VERDURAS', 'FAMILIAR');
INSERT INTO RECETAS (nombre, porcion)
VALUES('CORVINA AL HORNO A LA BILBAINA', 'MEDIANO');
INSERT INTO RECETAS (nombre, porcion)
VALUES('CORVINA EN SALSA VERDE', 'PERSONAL');
INSERT INTO RECETAS (nombre, porcion)
VALUES(
        'COSTILLA AL HORNO CON PATATAS PANADERA',
        'FAMILIAR'
    );
INSERT INTO RECETAS (nombre, porcion)
VALUES(
        'COSTILLA DE CERDO AL HORNO CON CERVEZA',
        'MEDIANO'
    );
INSERT INTO RECETAS (nombre, porcion)
VALUES(
        'COSTILLA DE CERDO AL HORNO CON MIEL Y MOSTAZA',
        'PERSONAL'
    );
INSERT INTO RECETAS (nombre, porcion)
VALUES('COSTILLA GUISADA SIN PATATAS', 'FAMILIAR');
INSERT INTO RECETAS (nombre, porcion)
VALUES('COSTILLAS DE CERDO EN SALSA BARBACOA', 'MEDIANO');
INSERT INTO RECETAS (nombre, porcion)
VALUES('COULANT DE CHOCOLATE RECETA', 'PERSONAL');
INSERT INTO RECETAS (nombre, porcion)
VALUES('CREMA CATALANA receta', 'FAMILIAR');
INSERT INTO RECETAS (nombre, porcion)
VALUES('CREMA DE BROCOLI', 'MEDIANO');
INSERT INTO RECETAS (nombre, porcion)
VALUES(
        'CREMA DE BRÓCOLI CON QUESO RECETA SENCILLA',
        'PERSONAL'
    );
INSERT INTO RECETAS (nombre, porcion)
VALUES('CREMA DE CALABACÍN CON QUESITOS', 'FAMILIAR');
INSERT INTO RECETAS (nombre, porcion)
VALUES('CREMA DE CALABACIN Y PUERRO', 'MEDIANO');
INSERT INTO RECETAS (nombre, porcion)
VALUES('CREMA DE CALABAZA', 'PERSONAL');
INSERT INTO RECETAS (nombre, porcion)
VALUES(
        'CREMA DE CALABAZA CON NATA PARA COCINAR.',
        'FAMILIAR'
    );
INSERT INTO RECETAS (nombre, porcion)
VALUES(
        'CREMA DE CALABAZA, ZANAHORIA Y CHAMPIÑONES',
        'MEDIANO'
    );
INSERT INTO RECETAS (nombre, porcion)
VALUES(
        'CREMA DE COLIFLOR ZANAHORIA Y PATATAS',
        'PERSONAL'
    );
INSERT INTO RECETAS (nombre, porcion)
VALUES('CREMA DE ESPARRAGOS BLANCOS', 'FAMILIAR');
INSERT INTO RECETAS (nombre, porcion)
VALUES('CREMA DE ESPARRAGOS VERDES', 'MEDIANO');
INSERT INTO RECETAS (nombre, porcion)
VALUES('CREMA DE ESPINACAS Y ZANAHORIA', 'PERSONAL');
INSERT INTO RECETAS (nombre, porcion)
VALUES('CREMA DE PUERROS', 'FAMILIAR');
INSERT INTO RECETAS (nombre, porcion)
VALUES('CREMA DE PUERROS Y PATATA', 'MEDIANO');
INSERT INTO RECETAS (nombre, porcion)
VALUES('CREMA DE ZANAHORIA Y PATATA', 'PERSONAL');
INSERT INTO RECETAS (nombre, porcion)
VALUES('CREMA FRIA DE CALABACIN Y AGUACATE', 'FAMILIAR');
INSERT INTO RECETAS (nombre, porcion)
VALUES('CREMA FRIA DE COLIFLOR Y MANZANA', 'MEDIANO');
INSERT INTO RECETAS (nombre, porcion)
VALUES('CREMA PASTELERA RECETA CASERA FACIL', 'PERSONAL');
INSERT INTO RECETAS (nombre, porcion)
VALUES(
        'CREPES DE CHOCOLATE, PLÁTANO Y NUECES',
        'FAMILIAR'
    );
INSERT INTO RECETAS (nombre, porcion)
VALUES('CREPES DULCES receta facil', 'MEDIANO');
INSERT INTO RECETAS (nombre, porcion)
VALUES(
        'CREPES RELLENOS DE ESPINACAS Y GAMBAS',
        'PERSONAL'
    );
INSERT INTO RECETAS (nombre, porcion)
VALUES('CREPS O CREPES SALADOS', 'FAMILIAR');
INSERT INTO RECETAS (nombre, porcion)
VALUES('CROQUETAS DE BACALAO', 'MEDIANO');
INSERT INTO RECETAS (nombre, porcion)
VALUES('CROQUETAS DE ESPINACAS Y PIÑONES', 'PERSONAL');
INSERT INTO RECETAS (nombre, porcion)
VALUES('CROQUETAS DE GAMBAS', 'FAMILIAR');
INSERT INTO RECETAS (nombre, porcion)
VALUES('CROQUETAS DE HONGOS', 'MEDIANO');
INSERT INTO RECETAS (nombre, porcion)
VALUES('CROQUETAS DE JAMON', 'PERSONAL');
INSERT INTO RECETAS (nombre, porcion)
VALUES('CROQUETAS DE POLLO CASERAS', 'FAMILIAR');
INSERT INTO RECETAS (nombre, porcion)
VALUES('CROQUETAS DE QUESO', 'MEDIANO');
INSERT INTO RECETAS (nombre, porcion)
VALUES('CUADRADITOS DE LIMON', 'PERSONAL');
INSERT INTO RECETAS (nombre, porcion)
VALUES(
        'CUSCUS CON VERDURAS Y POLLO AL CURRY',
        'FAMILIAR'
    );
INSERT INTO RECETAS (nombre, porcion)
VALUES('DATILES CON BACON', 'MEDIANO');
INSERT INTO RECETAS (nombre, porcion)
VALUES(
        'DESAYUNOS SALUDABLES FACILES Y RAPIDOS',
        'PERSONAL'
    );
INSERT INTO RECETAS (nombre, porcion)
VALUES('DIABETES TIPO 2 DIETA RECOMENDADA', 'FAMILIAR');
INSERT INTO RECETAS (nombre, porcion)
VALUES('DONUTS CASEROS AL HORNO', 'MEDIANO');
INSERT INTO RECETAS (nombre, porcion)
VALUES('DORADA A LA BILBAINA', 'PERSONAL');
INSERT INTO RECETAS (nombre, porcion)
VALUES('DORADA A LA PLANCHA', 'FAMILIAR');
INSERT INTO RECETAS (nombre, porcion)
VALUES(
        'DORADA A LA PLANCHA CON AJO Y PEREJIL',
        'MEDIANO'
    );
INSERT INTO RECETAS (nombre, porcion)
VALUES('DORADA A LA PLANCHA CON PATATAS', 'PERSONAL');
INSERT INTO RECETAS (nombre, porcion)
VALUES('DORADA A LA SAL AL HORNO', 'FAMILIAR');
INSERT INTO RECETAS (nombre, porcion)
VALUES('DORADA AL HORNO CON CEBOLLA Y TOMATE', 'MEDIANO');
INSERT INTO RECETAS (nombre, porcion)
VALUES(
        'DORADA AL HORNO CON PATATAS PANADERA, CEBOLLA Y VINO BLANCO',
        'PERSONAL'
    );
INSERT INTO RECETAS (nombre, porcion)
VALUES(
        'DORADA AL HORNO CON VERDURAS Y PATATAS',
        'FAMILIAR'
    );
INSERT INTO RECETAS (nombre, porcion)
VALUES('DORADA AL HORNO FACIL', 'MEDIANO');
INSERT INTO RECETAS (nombre, porcion)
VALUES('DULCE DE LECHE', 'PERSONAL');
INSERT INTO RECETAS (nombre, porcion)
VALUES(
        'EMPANADILLAS DE BONITO AL HORNO CASERAS',
        'FAMILIAR'
    );
INSERT INTO RECETAS (nombre, porcion)
VALUES(
        'EMPANADILLAS DE POLLO Y QUESO AL HORNO',
        'MEDIANO'
    );
INSERT INTO RECETAS (nombre, porcion)
VALUES('EMPANADILLAS DE VERDURAS AL HORNO', 'PERSONAL');
INSERT INTO RECETAS (nombre, porcion)
VALUES(
        'EMPANADILLAS RELLENAS DE ATUN AL HORNO',
        'FAMILIAR'
    );
INSERT INTO RECETAS (nombre, porcion)
VALUES('ENSALADA CAMPERA', 'MEDIANO');
INSERT INTO RECETAS (nombre, porcion)
VALUES('ENSALADA CAPRESE', 'PERSONAL');
INSERT INTO RECETAS (nombre, porcion)
VALUES(
        'ENSALADA CESAR receta casera con pollo',
        'FAMILIAR'
    );
INSERT INTO RECETAS (nombre, porcion)
VALUES('ENSALADA DE AGUACATE ATÚN Y TOMATE', 'MEDIANO');
INSERT INTO RECETAS (nombre, porcion)
VALUES('ENSALADA DE ARROZ', 'PERSONAL');
INSERT INTO RECETAS (nombre, porcion)
VALUES('ENSALADA DE ARROZ Y ATUN receta', 'FAMILIAR');
INSERT INTO RECETAS (nombre, porcion)
VALUES('ENSALADA DE BACALAO Y NARANJA', 'MEDIANO');
INSERT INTO RECETAS (nombre, porcion)
VALUES('ENSALADA DE CALABAZA Y AGUACATE', 'PERSONAL');
INSERT INTO RECETAS (nombre, porcion)
VALUES('ENSALADA DE COL receta', 'FAMILIAR');
INSERT INTO RECETAS (nombre, porcion)
VALUES('ENSALADA DE ENDIVIAS Y AGUACATE', 'MEDIANO');
INSERT INTO RECETAS (nombre, porcion)
VALUES('ENSALADA DE ESPINACAS Y NUECES', 'PERSONAL');
INSERT INTO RECETAS (nombre, porcion)
VALUES('ENSALADA DE GARBANZOS receta', 'FAMILIAR');
INSERT INTO RECETAS (nombre, porcion)
VALUES('ENSALADA DE GARBANZOS Y QUINOA', 'MEDIANO');
INSERT INTO RECETAS (nombre, porcion)
VALUES('ENSALADA DE GULAS Y GAMBAS', 'PERSONAL');
INSERT INTO RECETAS (nombre, porcion)
VALUES('ENSALADA DE LENTEJAS receta', 'FAMILIAR');
INSERT INTO RECETAS (nombre, porcion)
VALUES('ENSALADA DE MANZANA MEXICANA', 'MEDIANO');
INSERT INTO RECETAS (nombre, porcion)
VALUES('ENSALADA DE OTOÑO TEMPLADA', 'PERSONAL');
INSERT INTO RECETAS (nombre, porcion)
VALUES('ENSALADA DE PASTA CON ATUN', 'FAMILIAR');
INSERT INTO RECETAS (nombre, porcion)
VALUES(
        'ENSALADA DE PASTA CON POLLO AGUACATE Y QUESO',
        'MEDIANO'
    );
INSERT INTO RECETAS (nombre, porcion)
VALUES(
        'ENSALADA DE PASTA CON SALSA ROSA Y HUEVO',
        'PERSONAL'
    );
INSERT INTO RECETAS (nombre, porcion)
VALUES('ENSALADA DE PASTA receta', 'FAMILIAR');
INSERT INTO RECETAS (nombre, porcion)
VALUES('ENSALADA DE PATATA', 'MEDIANO');
INSERT INTO RECETAS (nombre, porcion)
VALUES('ENSALADA DE PATATA Y AGUACATE', 'PERSONAL');
INSERT INTO RECETAS (nombre, porcion)
VALUES('ENSALADA DE POLLO ANCHOAS Y QUESO', 'FAMILIAR');
INSERT INTO RECETAS (nombre, porcion)
VALUES('ENSALADA DE PULPO Y PATATAS', 'MEDIANO');
INSERT INTO RECETAS (nombre, porcion)
VALUES('ENSALADA DE QUESO DE CABRA', 'PERSONAL');
INSERT INTO RECETAS (nombre, porcion)
VALUES('ENSALADA DE QUESO DE CABRA Y NUECES', 'FAMILIAR');
INSERT INTO RECETAS (nombre, porcion)
VALUES('ENSALADA DE SALMON AHUMADO', 'MEDIANO');
INSERT INTO RECETAS (nombre, porcion)
VALUES('ENSALADA DE TOMATE Y ATUN', 'PERSONAL');
INSERT INTO RECETAS (nombre, porcion)
VALUES('ENSALADA GRIEGA receta original', 'FAMILIAR');
INSERT INTO RECETAS (nombre, porcion)
VALUES('ENSALADA MALAGUEÑA', 'MEDIANO');
INSERT INTO RECETAS (nombre, porcion)
VALUES('ENSALADA MIXTA CON ATÚN', 'PERSONAL');
INSERT INTO RECETAS (nombre, porcion)
VALUES('ENSALADA MURCIANA', 'FAMILIAR');
INSERT INTO RECETAS (nombre, porcion)
VALUES('ENSALADA NICOISE receta', 'MEDIANO');
INSERT INTO RECETAS (nombre, porcion)
VALUES('ENSALADA WALDORF', 'PERSONAL');
INSERT INTO RECETAS (nombre, porcion)
VALUES('ENSALADAS DE VERANO', 'FAMILIAR');
INSERT INTO RECETAS (nombre, porcion)
VALUES('ENSALADILLA DE CANGREJO', 'MEDIANO');
INSERT INTO RECETAS (nombre, porcion)
VALUES('ENSALADILLA RUSA receta', 'PERSONAL');
INSERT INTO RECETAS (nombre, porcion)
VALUES('ENTRECOT DE TERNERA A LA PLANCHA', 'FAMILIAR');
INSERT INTO RECETAS (nombre, porcion)
VALUES(
        'ENTRECOT DE TERNERA CON SALSA DE CHAMPIÑONES',
        'MEDIANO'
    );
INSERT INTO RECETAS (nombre, porcion)
VALUES('ESCALIVADA DE VERDURAS AL HORNO', 'PERSONAL');
INSERT INTO RECETAS (nombre, porcion)
VALUES(
        'ESCALOPINES DE TERNERA EN SALSA DE QUESO',
        'FAMILIAR'
    );
INSERT INTO RECETAS (nombre, porcion)
VALUES('ESENCIA DE VAINILLA CASERA', 'MEDIANO');
INSERT INTO RECETAS (nombre, porcion)
VALUES('ESPAGUETI A LA CREMA DE QUESO', 'PERSONAL');
INSERT INTO RECETAS (nombre, porcion)
VALUES(
        'ESPAGUETIS A LA BOLOÑESA RECETA ORIGINAL',
        'FAMILIAR'
    );
INSERT INTO RECETAS (nombre, porcion)
VALUES(
        'ESPAGUETIS A LA PUTTANESCA receta original',
        'MEDIANO'
    );
INSERT INTO RECETAS (nombre, porcion)
VALUES('ESPAGUETIS AL AJILLO CON GAMBAS', 'PERSONAL');
INSERT INTO RECETAS (nombre, porcion)
VALUES('ESPAGUETIS AL AJILLO receta', 'FAMILIAR');
INSERT INTO RECETAS (nombre, porcion)
VALUES(
        'ESPAGUETIS AL HORNO CON BECHAMEL Y CARNE',
        'MEDIANO'
    );
INSERT INTO RECETAS (nombre, porcion)
VALUES(
        'ESPAGUETIS CARBONARA RECETA TRADICIONAL',
        'PERSONAL'
    );
INSERT INTO RECETAS (nombre, porcion)
VALUES(
        'ESPAGUETIS CON CARNE PICADA Y TOMATE',
        'FAMILIAR'
    );
INSERT INTO RECETAS (nombre, porcion)
VALUES('ESPAGUETIS CON CHAMPIÑONES Y GAMBAS', 'MEDIANO');
INSERT INTO RECETAS (nombre, porcion)
VALUES('ESPAGUETIS CON GAMBAS Y GULAS', 'PERSONAL');
INSERT INTO RECETAS (nombre, porcion)
VALUES('ESPAGUETIS CON NATA Y ATUN', 'FAMILIAR');
INSERT INTO RECETAS (nombre, porcion)
VALUES(
        'ESPAGUETIS CON SALSA DE QUESO POLLO Y BACON',
        'MEDIANO'
    );
INSERT INTO RECETAS (nombre, porcion)
VALUES('ESPAGUETIS CON SETAS Y NATA', 'PERSONAL');
INSERT INTO RECETAS (nombre, porcion)
VALUES('ESPAGUETIS CON VERDURAS Y POLLO', 'FAMILIAR');
INSERT INTO RECETAS (nombre, porcion)
VALUES('ESPAGUETIS DE CALABACIN', 'MEDIANO');
INSERT INTO RECETAS (nombre, porcion)
VALUES('ESPAGUETIS DE CALABACIN CON GAMBAS', 'PERSONAL');
INSERT INTO RECETAS (nombre, porcion)
VALUES(
        'ESPAGUETIS EN SALSA ALFREDO CON POLLO',
        'FAMILIAR'
    );
INSERT INTO RECETAS (nombre, porcion)
VALUES(
        'ESPAGUETIS EN SALSA PESTO CASERA receta',
        'MEDIANO'
    );
INSERT INTO RECETAS (nombre, porcion)
VALUES(
        'ESPAGUETIS FANTASIA: Con salchichas pinchadas',
        'PERSONAL'
    );
INSERT INTO RECETAS (nombre, porcion)
VALUES('ESPAGUETIS ROJOS CON TOMATE', 'FAMILIAR');
INSERT INTO RECETAS (nombre, porcion)
VALUES(
        'ESPÁRRAGOS BLANCOS GRATINADOS CON BECHAMEL AL HORNO',
        'MEDIANO'
    );
INSERT INTO RECETAS (nombre, porcion)
VALUES('ESPÁRRAGOS RELLENOS DE LANGOSTINOS', 'PERSONAL');
INSERT INTO RECETAS (nombre, porcion)
VALUES(
        'ESPARRAGOS TRIGUEROS VERDES A LA PLANCHA',
        'FAMILIAR'
    );
INSERT INTO RECETAS (nombre, porcion)
VALUES(
        'ESPÁRRAGOS VERDES TRIGUEROS CON JAMÓN YORK Y QUESO',
        'MEDIANO'
    );
INSERT INTO RECETAS (nombre, porcion)
VALUES('ESPINACAS CON GAMBAS', 'PERSONAL');
INSERT INTO RECETAS (nombre, porcion)
VALUES('ESTOFADO DE TERNERA', 'FAMILIAR');
INSERT INTO RECETAS (nombre, porcion)
VALUES('FABES CON ALMEJAS receta', 'MEDIANO');
INSERT INTO RECETAS (nombre, porcion)
VALUES('FAJITAS DE POLLO MEXICANAS', 'PERSONAL');
INSERT INTO RECETAS (nombre, porcion)
VALUES('FAJITAS VEGETARIANAS CON GUACAMOLE', 'FAMILIAR');
INSERT INTO RECETAS (nombre, porcion)
VALUES('FALAFEL CASERO', 'MEDIANO');
INSERT INTO RECETAS (nombre, porcion)
VALUES('FALDA DE TERNERA AL HORNO RELLENA', 'PERSONAL');
INSERT INTO RECETAS (nombre, porcion)
VALUES('FIDEUA DE POLLO RECETA FACIL', 'FAMILIAR');
INSERT INTO RECETAS (nombre, porcion)
VALUES(
        'FILETES RUSOS DE CARNE DE POLLO AL HORNO',
        'MEDIANO'
    );
INSERT INTO RECETAS (nombre, porcion)
VALUES('FILETES RUSOS EN SALSA DE TOMATE', 'PERSONAL');
INSERT INTO RECETAS (nombre, porcion)
VALUES('FINGERS DE POLLO CASEROS', 'FAMILIAR');
INSERT INTO RECETAS (nombre, porcion)
VALUES('FINGERS DEDOS O PALITOS DE QUESO', 'MEDIANO');
INSERT INTO RECETAS (nombre, porcion)
VALUES('FLAMENQUINES CORDOBESES', 'PERSONAL');
INSERT INTO RECETAS (nombre, porcion)
VALUES('FLAN DE CALABAZA', 'FAMILIAR');
INSERT INTO RECETAS (nombre, porcion)
VALUES('FLAN DE HUEVO CASERO AL HORNO', 'MEDIANO');
INSERT INTO RECETAS (nombre, porcion)
VALUES('FLAN DE QUESO SIN HORNO', 'PERSONAL');
INSERT INTO RECETAS (nombre, porcion)
VALUES('FLAUTAS DE JAMON Y QUESO CASERAS', 'FAMILIAR');
INSERT INTO RECETAS (nombre, porcion)
VALUES('FLAUTAS DE POLLO MEXICANAS', 'MEDIANO');
INSERT INTO RECETAS (nombre, porcion)
VALUES('GALLETAS DE AVENA Y PLÁTANO', 'PERSONAL');
INSERT INTO RECETAS (nombre, porcion)
VALUES('GALLETAS DE MANTEQUILLA CASERAS', 'FAMILIAR');
INSERT INTO RECETAS (nombre, porcion)
VALUES(
        'GALLETAS DE MANTEQUILLA CON CHOCOLATE',
        'MEDIANO'
    );
INSERT INTO RECETAS (nombre, porcion)
VALUES('GALLETAS DE MANTEQUILLA Y NUECES', 'PERSONAL');
INSERT INTO RECETAS (nombre, porcion)
VALUES('GALLINA EN PEPITORIA', 'FAMILIAR');
INSERT INTO RECETAS (nombre, porcion)
VALUES(
        'GALLO AL HORNO CON CHAMPIÑONES Y PATATAS',
        'MEDIANO'
    );
INSERT INTO RECETAS (nombre, porcion)
VALUES('GAMBAS A LA GABARDINA receta', 'PERSONAL');
INSERT INTO RECETAS (nombre, porcion)
VALUES('GARBANZOS CON BERZA', 'FAMILIAR');
INSERT INTO RECETAS (nombre, porcion)
VALUES('GARBANZOS CON CARNE DE CERDO receta', 'MEDIANO');
INSERT INTO RECETAS (nombre, porcion)
VALUES('GARBANZOS CON ESPINACAS receta', 'PERSONAL');
INSERT INTO RECETAS (nombre, porcion)
VALUES('GARBANZOS CON VERDURAS Y POLLO', 'FAMILIAR');
INSERT INTO RECETAS (nombre, porcion)
VALUES('GAZPACHO ANDALUZ', 'MEDIANO');
INSERT INTO RECETAS (nombre, porcion)
VALUES('GELATINA DE FRESA NATURAL CASERA', 'PERSONAL');
INSERT INTO RECETAS (nombre, porcion)
VALUES('GUACAMOLE receta mexicana', 'FAMILIAR');
INSERT INTO RECETAS (nombre, porcion)
VALUES('GUISANTES CON JAMON Y HUEVO', 'MEDIANO');
INSERT INTO RECETAS (nombre, porcion)
VALUES('GUISO DE TERNERA CON CALABAZA', 'PERSONAL');
INSERT INTO RECETAS (nombre, porcion)
VALUES('HABAS CON JAMON RECETA FACIL', 'FAMILIAR');
INSERT INTO RECETAS (nombre, porcion)
VALUES('HAMBURGUESA CASERA receta', 'MEDIANO');
INSERT INTO RECETAS (nombre, porcion)
VALUES('HAMBURGUESA CASERA RELLENA DE QUESO', 'PERSONAL');
INSERT INTO RECETAS (nombre, porcion)
VALUES(
        'HAMBURGUESA DE LENTEJAS Y ARROZ facil',
        'FAMILIAR'
    );
INSERT INTO RECETAS (nombre, porcion)
VALUES('HAMBURGUESA DE POLLO CASERA', 'MEDIANO');
INSERT INTO RECETAS (nombre, porcion)
VALUES('HAMBURGUESA DE POLLO estilo nugget', 'PERSONAL');
INSERT INTO RECETAS (nombre, porcion)
VALUES('HAMBURGUESA DE POLLO Y ESPINACAS', 'FAMILIAR');
INSERT INTO RECETAS (nombre, porcion)
VALUES('HAMBURGUESA DE POLLO Y ZANAHORIA', 'MEDIANO');
INSERT INTO RECETAS (nombre, porcion)
VALUES('HAMBURGUESA DE TOFU Y GARBANZOS', 'PERSONAL');
INSERT INTO RECETAS (nombre, porcion)
VALUES('HAMBURGUESA DOBLE CON QUESO', 'FAMILIAR');
INSERT INTO RECETAS (nombre, porcion)
VALUES('HAMBURGUESAS VEGANAS', 'MEDIANO');
INSERT INTO RECETAS (nombre, porcion)
VALUES('HIGADO ENCEBOLLADO', 'PERSONAL');
INSERT INTO RECETAS (nombre, porcion)
VALUES(
        'HOGAZA DE PAN CASERO. RECETA TRADICIONAL.',
        'FAMILIAR'
    );
INSERT INTO RECETAS (nombre, porcion)
VALUES('HOJALDRE DE CABELLO DE ANGEL', 'MEDIANO');
INSERT INTO RECETAS (nombre, porcion)
VALUES('HOJALDRE RELLENO DE VERDURAS', 'PERSONAL');
INSERT INTO RECETAS (nombre, porcion)
VALUES('HUESOS DE SANTO', 'FAMILIAR');
INSERT INTO RECETAS (nombre, porcion)
VALUES('HUEVO EN CANASTA O HUEVO EN PAN', 'MEDIANO');
INSERT INTO RECETAS (nombre, porcion)
VALUES('HUEVOS ESCALFADOS', 'PERSONAL');
INSERT INTO RECETAS (nombre, porcion)
VALUES(
        'HUEVOS RELLENOS DE ATUN CON BECHAMEL',
        'FAMILIAR'
    );
INSERT INTO RECETAS (nombre, porcion)
VALUES(
        'HUEVOS RELLENOS DE CARNE PICADA AL HORNO',
        'MEDIANO'
    );
INSERT INTO RECETAS (nombre, porcion)
VALUES('HUEVOS RELLENOS DE GAMBAS Y SURIMI', 'PERSONAL');
INSERT INTO RECETAS (nombre, porcion)
VALUES('HUEVOS REVUELTOS CON ESPINACAS', 'FAMILIAR');
INSERT INTO RECETAS (nombre, porcion)
VALUES(
        'HUEVOS ROTOS CON BACON, PATATAS Y QUESO',
        'MEDIANO'
    );
INSERT INTO RECETAS (nombre, porcion)
VALUES('HUEVOS ROTOS CON PATATAS FRITAS', 'PERSONAL');
INSERT INTO RECETAS (nombre, porcion)
VALUES('HUMMUS CASERO', 'FAMILIAR');
INSERT INTO RECETAS (nombre, porcion)
VALUES('JUDIAS VERDES CON PATATAS', 'MEDIANO');
INSERT INTO RECETAS (nombre, porcion)
VALUES('JUDIAS VERDES CON PATATAS Y JAMON', 'PERSONAL');
INSERT INTO RECETAS (nombre, porcion)
VALUES('JUGO DE VERDURAS para diabéticos', 'FAMILIAR');
INSERT INTO RECETAS (nombre, porcion)
VALUES('LANGOSTINOS AL HORNO', 'MEDIANO');
INSERT INTO RECETAS (nombre, porcion)
VALUES('LASAÑA DE CALABACIN JAMON Y QUESO', 'PERSONAL');
INSERT INTO RECETAS (nombre, porcion)
VALUES('LASAÑA DE CALABAZA Y ESPINACAS', 'FAMILIAR');
INSERT INTO RECETAS (nombre, porcion)
VALUES('LASAÑA DE CARNE PICADA Y BECHAMEL', 'MEDIANO');
INSERT INTO RECETAS (nombre, porcion)
VALUES('LASAÑA DE CARNE SIN HORNO', 'PERSONAL');
INSERT INTO RECETAS (nombre, porcion)
VALUES('LASAÑA DE PAN DE MOLDE', 'FAMILIAR');
INSERT INTO RECETAS (nombre, porcion)
VALUES('LASAÑA DE PATATA Y POLLO', 'MEDIANO');
INSERT INTO RECETAS (nombre, porcion)
VALUES('LASAÑA DE VERDURAS FACIL', 'PERSONAL');
INSERT INTO RECETAS (nombre, porcion)
VALUES('LASAÑA DE VERDURAS Y ATUN', 'FAMILIAR');
INSERT INTO RECETAS (nombre, porcion)
VALUES('LASAÑA PIZZA', 'MEDIANO');
INSERT INTO RECETAS (nombre, porcion)
VALUES('LECHAZO ASADO AL HORNO ELECTRICO', 'PERSONAL');
INSERT INTO RECETAS (nombre, porcion)
VALUES('LECHE FRITA receta', 'FAMILIAR');
INSERT INTO RECETAS (nombre, porcion)
VALUES(
        'LENTEJAS CON CHORIZO Y COSTILLA DE CERDO',
        'MEDIANO'
    );
INSERT INTO RECETAS (nombre, porcion)
VALUES('LENTEJAS CON VERDURAS receta', 'PERSONAL');
INSERT INTO RECETAS (nombre, porcion)
VALUES('LOMO AL HORNO JUGOSO Y TIERNO', 'FAMILIAR');
INSERT INTO RECETAS (nombre, porcion)
VALUES('LOMO DE CERDO A LA SAL', 'MEDIANO');
INSERT INTO RECETAS (nombre, porcion)
VALUES('LOMO EN SALSA DE CEBOLLA', 'PERSONAL');
INSERT INTO RECETAS (nombre, porcion)
VALUES(
        'LOMOS DE BACALAO FRESCO AL HORNO CON PIMIENTOS',
        'FAMILIAR'
    );
INSERT INTO RECETAS (nombre, porcion)
VALUES('LUBINA A LA DONOSTIARRA', 'MEDIANO');
INSERT INTO RECETAS (nombre, porcion)
VALUES('LUBINA A LA ESPALDA', 'PERSONAL');
INSERT INTO RECETAS (nombre, porcion)
VALUES('LUBINA A LA PLANCHA CON VERDURAS', 'FAMILIAR');
INSERT INTO RECETAS (nombre, porcion)
VALUES(
        'LUBINA A LA PLANCHA EN SALSA VINAGRETA',
        'MEDIANO'
    );
INSERT INTO RECETAS (nombre, porcion)
VALUES('LUBINA A LA SAL AL HORNO', 'PERSONAL');
INSERT INTO RECETAS (nombre, porcion)
VALUES('LUBINA AL HORNO CON NARANJA', 'FAMILIAR');
INSERT INTO RECETAS (nombre, porcion)
VALUES('LUBINA AL HORNO CON PATATAS', 'MEDIANO');
INSERT INTO RECETAS (nombre, porcion)
VALUES('LUBINA EN SALSA VERDE', 'PERSONAL');
INSERT INTO RECETAS (nombre, porcion)
VALUES(
        'MACARRONES CARBONARA receta original',
        'FAMILIAR'
    );
INSERT INTO RECETAS (nombre, porcion)
VALUES('MACARRONES CON ATUN GRATINADOS', 'MEDIANO');
INSERT INTO RECETAS (nombre, porcion)
VALUES(
        'MACARRONES CON CARNE PICADA Y TOMATE',
        'PERSONAL'
    );
INSERT INTO RECETAS (nombre, porcion)
VALUES(
        'MACARRONES CON QUESO GRATINADO AL HORNO',
        'FAMILIAR'
    );
INSERT INTO RECETAS (nombre, porcion)
VALUES('MACARRONES CON TOMATE AL HORNO', 'MEDIANO');
INSERT INTO RECETAS (nombre, porcion)
VALUES('MACARRONES CON TOMATE Y ATUN receta', 'PERSONAL');
INSERT INTO RECETAS (nombre, porcion)
VALUES('MACARRONES CON TOMATE Y CHORIZO', 'FAMILIAR');
INSERT INTO RECETAS (nombre, porcion)
VALUES('MACARRONES CON VERDURAS', 'MEDIANO');
INSERT INTO RECETAS (nombre, porcion)
VALUES(
        'MACEDONIA DE FRUTAS SENCILLA CON CHOCOLATE Y FRUTOS SECOS',
        'PERSONAL'
    );
INSERT INTO RECETAS (nombre, porcion)
VALUES('MAGDALENAS DE CHOCOLATE CASERAS', 'FAMILIAR');
INSERT INTO RECETAS (nombre, porcion)
VALUES('MAGDALENAS DE NARANJA Y YOGUR', 'MEDIANO');
INSERT INTO RECETAS (nombre, porcion)
VALUES('MAGRET DE PATO A LA PLANCHA', 'PERSONAL');
INSERT INTO RECETAS (nombre, porcion)
VALUES(
        'MARMITAKO DE BONITO receta tradicional',
        'FAMILIAR'
    );
INSERT INTO RECETAS (nombre, porcion)
VALUES('MASA MADRE PARA PREPARAR PAN CASERO', 'MEDIANO');
INSERT INTO RECETAS (nombre, porcion)
VALUES('MAYONESA CASERA FACIL', 'PERSONAL');
INSERT INTO RECETAS (nombre, porcion)
VALUES('MAYONESA CASERA SIN HUEVO', 'FAMILIAR');
INSERT INTO RECETAS (nombre, porcion)
VALUES(
        'MAYONESA CORTADA que es y como recuperar',
        'MEDIANO'
    );
INSERT INTO RECETAS (nombre, porcion)
VALUES('MEJILLONES A LA ESCOCESA receta', 'PERSONAL');